apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rebellis.fullname" . }}-default-deny
spec:
  podSelector: {}
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
      - podSelector: {}
  egress:
    - to:
      - podSelector: {}
