apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rebellis.fullname" . }}-motion
spec:
  minAvailable: 1
  selector:
    matchLabels: { app: {{ include "rebellis.fullname" . }}-motion }
