{{- if and .Values.monitoring.enabled .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "rebellis.fullname" . }}-api
  labels: { release: prometheus }
{{- with .Values.prometheusRule.labels }}{{ toYaml . | indent 2 }}{{- end }}
spec:
  groups: {{- toYaml .Values.prometheusRule.groups | nindent 4 }}
{{- end }}
