apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rebellis.fullname" . }}-api
  {{- if and .Values.gcp.workloadIdentity.enabled .Values.gcp.workloadIdentity.apiGsaEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentity.apiGsaEmail | quote }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rebellis.fullname" . }}-whisper
  {{- if and .Values.gcp.workloadIdentity.enabled .Values.gcp.workloadIdentity.whisperGsaEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentity.whisperGsaEmail | quote }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rebellis.fullname" . }}-motion
  {{- if and .Values.gcp.workloadIdentity.enabled .Values.gcp.workloadIdentity.motionGsaEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentity.motionGsaEmail | quote }}
  {{- end }}
