global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'whisper'
    static_configs:
      - targets: ['whisper:8081']
  - job_name: 'motion'
    static_configs:
      - targets: ['motion:8082']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml
